/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TableSelectionRouteImport } from './routes/TableSelection'
import { Route as ScanQRRouteImport } from './routes/ScanQR'
import { Route as LandingPageRouteImport } from './routes/LandingPage'
import { Route as EditValueRouteImport } from './routes/EditValue'
import { Route as AdminPageRouteImport } from './routes/AdminPage'
import { Route as AddValueRouteImport } from './routes/AddValue'
import { Route as TableRouteRouteImport } from './routes/table/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as TableVendorRouteImport } from './routes/table/Vendor'
import { Route as TableRoleRouteImport } from './routes/table/Role'
import { Route as TableQRPageRouteImport } from './routes/table/QRPage'
import { Route as TableProductSetRouteImport } from './routes/table/ProductSet'
import { Route as TableProductRouteImport } from './routes/table/Product'
import { Route as TableManufacturerRouteImport } from './routes/table/Manufacturer'
import { Route as TableLocationRouteImport } from './routes/table/Location'
import { Route as TableEndUserRoleRouteImport } from './routes/table/EndUserRole'
import { Route as TableEndUserRouteImport } from './routes/table/EndUser'
import { Route as TableEmployeeRouteImport } from './routes/table/Employee'
import { Route as TableDepartmentRouteImport } from './routes/table/Department'
import { Route as TableCompanyRouteImport } from './routes/table/Company'
import { Route as TableCategoryRouteImport } from './routes/table/Category'
import { Route as TableBuildingRouteImport } from './routes/table/Building'
import { Route as TableAssetTransferRouteImport } from './routes/table/AssetTransfer'
import { Route as TableAssetIssueRouteImport } from './routes/table/AssetIssue'
import { Route as TableAssetFixRouteImport } from './routes/table/AssetFix'
import { Route as TableAssetRouteImport } from './routes/table/Asset'
import { Route as AdminpagesRegisterUserRouteImport } from './routes/adminpages/RegisterUser'
import { Route as AdminpagesManageUserRouteImport } from './routes/adminpages/ManageUser'
import { Route as AdminpagesManageTableRouteImport } from './routes/adminpages/ManageTable'
import { Route as AdminpagesAdminPageRouteImport } from './routes/adminpages/AdminPage'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TableSelectionRoute = TableSelectionRouteImport.update({
  id: '/TableSelection',
  path: '/TableSelection',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanQRRoute = ScanQRRouteImport.update({
  id: '/ScanQR',
  path: '/ScanQR',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/LandingPage',
  path: '/LandingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const EditValueRoute = EditValueRouteImport.update({
  id: '/EditValue',
  path: '/EditValue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/AdminPage',
  path: '/AdminPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AddValueRoute = AddValueRouteImport.update({
  id: '/AddValue',
  path: '/AddValue',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRouteRoute = TableRouteRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableVendorRoute = TableVendorRouteImport.update({
  id: '/Vendor',
  path: '/Vendor',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableRoleRoute = TableRoleRouteImport.update({
  id: '/Role',
  path: '/Role',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableQRPageRoute = TableQRPageRouteImport.update({
  id: '/QRPage',
  path: '/QRPage',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableProductSetRoute = TableProductSetRouteImport.update({
  id: '/ProductSet',
  path: '/ProductSet',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableProductRoute = TableProductRouteImport.update({
  id: '/Product',
  path: '/Product',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableManufacturerRoute = TableManufacturerRouteImport.update({
  id: '/Manufacturer',
  path: '/Manufacturer',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableLocationRoute = TableLocationRouteImport.update({
  id: '/Location',
  path: '/Location',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableEndUserRoleRoute = TableEndUserRoleRouteImport.update({
  id: '/EndUserRole',
  path: '/EndUserRole',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableEndUserRoute = TableEndUserRouteImport.update({
  id: '/EndUser',
  path: '/EndUser',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableEmployeeRoute = TableEmployeeRouteImport.update({
  id: '/Employee',
  path: '/Employee',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableDepartmentRoute = TableDepartmentRouteImport.update({
  id: '/Department',
  path: '/Department',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableCompanyRoute = TableCompanyRouteImport.update({
  id: '/Company',
  path: '/Company',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableCategoryRoute = TableCategoryRouteImport.update({
  id: '/Category',
  path: '/Category',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableBuildingRoute = TableBuildingRouteImport.update({
  id: '/Building',
  path: '/Building',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableAssetTransferRoute = TableAssetTransferRouteImport.update({
  id: '/AssetTransfer',
  path: '/AssetTransfer',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableAssetIssueRoute = TableAssetIssueRouteImport.update({
  id: '/AssetIssue',
  path: '/AssetIssue',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableAssetFixRoute = TableAssetFixRouteImport.update({
  id: '/AssetFix',
  path: '/AssetFix',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableAssetRoute = TableAssetRouteImport.update({
  id: '/Asset',
  path: '/Asset',
  getParentRoute: () => TableRouteRoute,
} as any)
const AdminpagesRegisterUserRoute = AdminpagesRegisterUserRouteImport.update({
  id: '/adminpages/RegisterUser',
  path: '/adminpages/RegisterUser',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpagesManageUserRoute = AdminpagesManageUserRouteImport.update({
  id: '/adminpages/ManageUser',
  path: '/adminpages/ManageUser',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpagesManageTableRoute = AdminpagesManageTableRouteImport.update({
  id: '/adminpages/ManageTable',
  path: '/adminpages/ManageTable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpagesAdminPageRoute = AdminpagesAdminPageRouteImport.update({
  id: '/adminpages/AdminPage',
  path: '/adminpages/AdminPage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/table': typeof TableRouteRouteWithChildren
  '/AddValue': typeof AddValueRoute
  '/AdminPage': typeof AdminPageRoute
  '/EditValue': typeof EditValueRoute
  '/LandingPage': typeof LandingPageRoute
  '/ScanQR': typeof ScanQRRoute
  '/TableSelection': typeof TableSelectionRoute
  '/about': typeof AboutRoute
  '/adminpages/AdminPage': typeof AdminpagesAdminPageRoute
  '/adminpages/ManageTable': typeof AdminpagesManageTableRoute
  '/adminpages/ManageUser': typeof AdminpagesManageUserRoute
  '/adminpages/RegisterUser': typeof AdminpagesRegisterUserRoute
  '/table/Asset': typeof TableAssetRoute
  '/table/AssetFix': typeof TableAssetFixRoute
  '/table/AssetIssue': typeof TableAssetIssueRoute
  '/table/AssetTransfer': typeof TableAssetTransferRoute
  '/table/Building': typeof TableBuildingRoute
  '/table/Category': typeof TableCategoryRoute
  '/table/Company': typeof TableCompanyRoute
  '/table/Department': typeof TableDepartmentRoute
  '/table/Employee': typeof TableEmployeeRoute
  '/table/EndUser': typeof TableEndUserRoute
  '/table/EndUserRole': typeof TableEndUserRoleRoute
  '/table/Location': typeof TableLocationRoute
  '/table/Manufacturer': typeof TableManufacturerRoute
  '/table/Product': typeof TableProductRoute
  '/table/ProductSet': typeof TableProductSetRoute
  '/table/QRPage': typeof TableQRPageRoute
  '/table/Role': typeof TableRoleRoute
  '/table/Vendor': typeof TableVendorRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AddValue': typeof AddValueRoute
  '/AdminPage': typeof AdminPageRoute
  '/EditValue': typeof EditValueRoute
  '/LandingPage': typeof LandingPageRoute
  '/ScanQR': typeof ScanQRRoute
  '/TableSelection': typeof TableSelectionRoute
  '/about': typeof AboutRoute
  '/adminpages/AdminPage': typeof AdminpagesAdminPageRoute
  '/adminpages/ManageTable': typeof AdminpagesManageTableRoute
  '/adminpages/ManageUser': typeof AdminpagesManageUserRoute
  '/adminpages/RegisterUser': typeof AdminpagesRegisterUserRoute
  '/table/Asset': typeof TableAssetRoute
  '/table/AssetFix': typeof TableAssetFixRoute
  '/table/AssetIssue': typeof TableAssetIssueRoute
  '/table/AssetTransfer': typeof TableAssetTransferRoute
  '/table/Building': typeof TableBuildingRoute
  '/table/Category': typeof TableCategoryRoute
  '/table/Company': typeof TableCompanyRoute
  '/table/Department': typeof TableDepartmentRoute
  '/table/Employee': typeof TableEmployeeRoute
  '/table/EndUser': typeof TableEndUserRoute
  '/table/EndUserRole': typeof TableEndUserRoleRoute
  '/table/Location': typeof TableLocationRoute
  '/table/Manufacturer': typeof TableManufacturerRoute
  '/table/Product': typeof TableProductRoute
  '/table/ProductSet': typeof TableProductSetRoute
  '/table/QRPage': typeof TableQRPageRoute
  '/table/Role': typeof TableRoleRoute
  '/table/Vendor': typeof TableVendorRoute
  '/table': typeof TableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/table': typeof TableRouteRouteWithChildren
  '/AddValue': typeof AddValueRoute
  '/AdminPage': typeof AdminPageRoute
  '/EditValue': typeof EditValueRoute
  '/LandingPage': typeof LandingPageRoute
  '/ScanQR': typeof ScanQRRoute
  '/TableSelection': typeof TableSelectionRoute
  '/about': typeof AboutRoute
  '/adminpages/AdminPage': typeof AdminpagesAdminPageRoute
  '/adminpages/ManageTable': typeof AdminpagesManageTableRoute
  '/adminpages/ManageUser': typeof AdminpagesManageUserRoute
  '/adminpages/RegisterUser': typeof AdminpagesRegisterUserRoute
  '/table/Asset': typeof TableAssetRoute
  '/table/AssetFix': typeof TableAssetFixRoute
  '/table/AssetIssue': typeof TableAssetIssueRoute
  '/table/AssetTransfer': typeof TableAssetTransferRoute
  '/table/Building': typeof TableBuildingRoute
  '/table/Category': typeof TableCategoryRoute
  '/table/Company': typeof TableCompanyRoute
  '/table/Department': typeof TableDepartmentRoute
  '/table/Employee': typeof TableEmployeeRoute
  '/table/EndUser': typeof TableEndUserRoute
  '/table/EndUserRole': typeof TableEndUserRoleRoute
  '/table/Location': typeof TableLocationRoute
  '/table/Manufacturer': typeof TableManufacturerRoute
  '/table/Product': typeof TableProductRoute
  '/table/ProductSet': typeof TableProductSetRoute
  '/table/QRPage': typeof TableQRPageRoute
  '/table/Role': typeof TableRoleRoute
  '/table/Vendor': typeof TableVendorRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/table'
    | '/AddValue'
    | '/AdminPage'
    | '/EditValue'
    | '/LandingPage'
    | '/ScanQR'
    | '/TableSelection'
    | '/about'
    | '/adminpages/AdminPage'
    | '/adminpages/ManageTable'
    | '/adminpages/ManageUser'
    | '/adminpages/RegisterUser'
    | '/table/Asset'
    | '/table/AssetFix'
    | '/table/AssetIssue'
    | '/table/AssetTransfer'
    | '/table/Building'
    | '/table/Category'
    | '/table/Company'
    | '/table/Department'
    | '/table/Employee'
    | '/table/EndUser'
    | '/table/EndUserRole'
    | '/table/Location'
    | '/table/Manufacturer'
    | '/table/Product'
    | '/table/ProductSet'
    | '/table/QRPage'
    | '/table/Role'
    | '/table/Vendor'
    | '/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AddValue'
    | '/AdminPage'
    | '/EditValue'
    | '/LandingPage'
    | '/ScanQR'
    | '/TableSelection'
    | '/about'
    | '/adminpages/AdminPage'
    | '/adminpages/ManageTable'
    | '/adminpages/ManageUser'
    | '/adminpages/RegisterUser'
    | '/table/Asset'
    | '/table/AssetFix'
    | '/table/AssetIssue'
    | '/table/AssetTransfer'
    | '/table/Building'
    | '/table/Category'
    | '/table/Company'
    | '/table/Department'
    | '/table/Employee'
    | '/table/EndUser'
    | '/table/EndUserRole'
    | '/table/Location'
    | '/table/Manufacturer'
    | '/table/Product'
    | '/table/ProductSet'
    | '/table/QRPage'
    | '/table/Role'
    | '/table/Vendor'
    | '/table'
  id:
    | '__root__'
    | '/'
    | '/table'
    | '/AddValue'
    | '/AdminPage'
    | '/EditValue'
    | '/LandingPage'
    | '/ScanQR'
    | '/TableSelection'
    | '/about'
    | '/adminpages/AdminPage'
    | '/adminpages/ManageTable'
    | '/adminpages/ManageUser'
    | '/adminpages/RegisterUser'
    | '/table/Asset'
    | '/table/AssetFix'
    | '/table/AssetIssue'
    | '/table/AssetTransfer'
    | '/table/Building'
    | '/table/Category'
    | '/table/Company'
    | '/table/Department'
    | '/table/Employee'
    | '/table/EndUser'
    | '/table/EndUserRole'
    | '/table/Location'
    | '/table/Manufacturer'
    | '/table/Product'
    | '/table/ProductSet'
    | '/table/QRPage'
    | '/table/Role'
    | '/table/Vendor'
    | '/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableRouteRoute: typeof TableRouteRouteWithChildren
  AddValueRoute: typeof AddValueRoute
  AdminPageRoute: typeof AdminPageRoute
  EditValueRoute: typeof EditValueRoute
  LandingPageRoute: typeof LandingPageRoute
  ScanQRRoute: typeof ScanQRRoute
  TableSelectionRoute: typeof TableSelectionRoute
  AboutRoute: typeof AboutRoute
  AdminpagesAdminPageRoute: typeof AdminpagesAdminPageRoute
  AdminpagesManageTableRoute: typeof AdminpagesManageTableRoute
  AdminpagesManageUserRoute: typeof AdminpagesManageUserRoute
  AdminpagesRegisterUserRoute: typeof AdminpagesRegisterUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TableSelection': {
      id: '/TableSelection'
      path: '/TableSelection'
      fullPath: '/TableSelection'
      preLoaderRoute: typeof TableSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ScanQR': {
      id: '/ScanQR'
      path: '/ScanQR'
      fullPath: '/ScanQR'
      preLoaderRoute: typeof ScanQRRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LandingPage': {
      id: '/LandingPage'
      path: '/LandingPage'
      fullPath: '/LandingPage'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/EditValue': {
      id: '/EditValue'
      path: '/EditValue'
      fullPath: '/EditValue'
      preLoaderRoute: typeof EditValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminPage': {
      id: '/AdminPage'
      path: '/AdminPage'
      fullPath: '/AdminPage'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AddValue': {
      id: '/AddValue'
      path: '/AddValue'
      fullPath: '/AddValue'
      preLoaderRoute: typeof AddValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Vendor': {
      id: '/table/Vendor'
      path: '/Vendor'
      fullPath: '/table/Vendor'
      preLoaderRoute: typeof TableVendorRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Role': {
      id: '/table/Role'
      path: '/Role'
      fullPath: '/table/Role'
      preLoaderRoute: typeof TableRoleRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/QRPage': {
      id: '/table/QRPage'
      path: '/QRPage'
      fullPath: '/table/QRPage'
      preLoaderRoute: typeof TableQRPageRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/ProductSet': {
      id: '/table/ProductSet'
      path: '/ProductSet'
      fullPath: '/table/ProductSet'
      preLoaderRoute: typeof TableProductSetRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Product': {
      id: '/table/Product'
      path: '/Product'
      fullPath: '/table/Product'
      preLoaderRoute: typeof TableProductRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Manufacturer': {
      id: '/table/Manufacturer'
      path: '/Manufacturer'
      fullPath: '/table/Manufacturer'
      preLoaderRoute: typeof TableManufacturerRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Location': {
      id: '/table/Location'
      path: '/Location'
      fullPath: '/table/Location'
      preLoaderRoute: typeof TableLocationRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/EndUserRole': {
      id: '/table/EndUserRole'
      path: '/EndUserRole'
      fullPath: '/table/EndUserRole'
      preLoaderRoute: typeof TableEndUserRoleRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/EndUser': {
      id: '/table/EndUser'
      path: '/EndUser'
      fullPath: '/table/EndUser'
      preLoaderRoute: typeof TableEndUserRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Employee': {
      id: '/table/Employee'
      path: '/Employee'
      fullPath: '/table/Employee'
      preLoaderRoute: typeof TableEmployeeRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Department': {
      id: '/table/Department'
      path: '/Department'
      fullPath: '/table/Department'
      preLoaderRoute: typeof TableDepartmentRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Company': {
      id: '/table/Company'
      path: '/Company'
      fullPath: '/table/Company'
      preLoaderRoute: typeof TableCompanyRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Category': {
      id: '/table/Category'
      path: '/Category'
      fullPath: '/table/Category'
      preLoaderRoute: typeof TableCategoryRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Building': {
      id: '/table/Building'
      path: '/Building'
      fullPath: '/table/Building'
      preLoaderRoute: typeof TableBuildingRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/AssetTransfer': {
      id: '/table/AssetTransfer'
      path: '/AssetTransfer'
      fullPath: '/table/AssetTransfer'
      preLoaderRoute: typeof TableAssetTransferRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/AssetIssue': {
      id: '/table/AssetIssue'
      path: '/AssetIssue'
      fullPath: '/table/AssetIssue'
      preLoaderRoute: typeof TableAssetIssueRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/AssetFix': {
      id: '/table/AssetFix'
      path: '/AssetFix'
      fullPath: '/table/AssetFix'
      preLoaderRoute: typeof TableAssetFixRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Asset': {
      id: '/table/Asset'
      path: '/Asset'
      fullPath: '/table/Asset'
      preLoaderRoute: typeof TableAssetRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/adminpages/RegisterUser': {
      id: '/adminpages/RegisterUser'
      path: '/adminpages/RegisterUser'
      fullPath: '/adminpages/RegisterUser'
      preLoaderRoute: typeof AdminpagesRegisterUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpages/ManageUser': {
      id: '/adminpages/ManageUser'
      path: '/adminpages/ManageUser'
      fullPath: '/adminpages/ManageUser'
      preLoaderRoute: typeof AdminpagesManageUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpages/ManageTable': {
      id: '/adminpages/ManageTable'
      path: '/adminpages/ManageTable'
      fullPath: '/adminpages/ManageTable'
      preLoaderRoute: typeof AdminpagesManageTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpages/AdminPage': {
      id: '/adminpages/AdminPage'
      path: '/adminpages/AdminPage'
      fullPath: '/adminpages/AdminPage'
      preLoaderRoute: typeof AdminpagesAdminPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TableRouteRouteChildren {
  TableAssetRoute: typeof TableAssetRoute
  TableAssetFixRoute: typeof TableAssetFixRoute
  TableAssetIssueRoute: typeof TableAssetIssueRoute
  TableAssetTransferRoute: typeof TableAssetTransferRoute
  TableBuildingRoute: typeof TableBuildingRoute
  TableCategoryRoute: typeof TableCategoryRoute
  TableCompanyRoute: typeof TableCompanyRoute
  TableDepartmentRoute: typeof TableDepartmentRoute
  TableEmployeeRoute: typeof TableEmployeeRoute
  TableEndUserRoute: typeof TableEndUserRoute
  TableEndUserRoleRoute: typeof TableEndUserRoleRoute
  TableLocationRoute: typeof TableLocationRoute
  TableManufacturerRoute: typeof TableManufacturerRoute
  TableProductRoute: typeof TableProductRoute
  TableProductSetRoute: typeof TableProductSetRoute
  TableQRPageRoute: typeof TableQRPageRoute
  TableRoleRoute: typeof TableRoleRoute
  TableVendorRoute: typeof TableVendorRoute
  TableIndexRoute: typeof TableIndexRoute
}

const TableRouteRouteChildren: TableRouteRouteChildren = {
  TableAssetRoute: TableAssetRoute,
  TableAssetFixRoute: TableAssetFixRoute,
  TableAssetIssueRoute: TableAssetIssueRoute,
  TableAssetTransferRoute: TableAssetTransferRoute,
  TableBuildingRoute: TableBuildingRoute,
  TableCategoryRoute: TableCategoryRoute,
  TableCompanyRoute: TableCompanyRoute,
  TableDepartmentRoute: TableDepartmentRoute,
  TableEmployeeRoute: TableEmployeeRoute,
  TableEndUserRoute: TableEndUserRoute,
  TableEndUserRoleRoute: TableEndUserRoleRoute,
  TableLocationRoute: TableLocationRoute,
  TableManufacturerRoute: TableManufacturerRoute,
  TableProductRoute: TableProductRoute,
  TableProductSetRoute: TableProductSetRoute,
  TableQRPageRoute: TableQRPageRoute,
  TableRoleRoute: TableRoleRoute,
  TableVendorRoute: TableVendorRoute,
  TableIndexRoute: TableIndexRoute,
}

const TableRouteRouteWithChildren = TableRouteRoute._addFileChildren(
  TableRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableRouteRoute: TableRouteRouteWithChildren,
  AddValueRoute: AddValueRoute,
  AdminPageRoute: AdminPageRoute,
  EditValueRoute: EditValueRoute,
  LandingPageRoute: LandingPageRoute,
  ScanQRRoute: ScanQRRoute,
  TableSelectionRoute: TableSelectionRoute,
  AboutRoute: AboutRoute,
  AdminpagesAdminPageRoute: AdminpagesAdminPageRoute,
  AdminpagesManageTableRoute: AdminpagesManageTableRoute,
  AdminpagesManageUserRoute: AdminpagesManageUserRoute,
  AdminpagesRegisterUserRoute: AdminpagesRegisterUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
