/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TableSelectionRouteImport } from './routes/TableSelection'
import { Route as ScanQRRouteImport } from './routes/ScanQR'
import { Route as LandingPageRouteImport } from './routes/LandingPage'
import { Route as EditValueRouteImport } from './routes/EditValue'
import { Route as AdminPageRouteImport } from './routes/AdminPage'
import { Route as AddValueRouteImport } from './routes/AddValue'
import { Route as TableRouteRouteImport } from './routes/table/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as TableQRPageRouteImport } from './routes/table/QRPage'
import { Route as TableAssetRouteImport } from './routes/table/Asset'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TableSelectionRoute = TableSelectionRouteImport.update({
  id: '/TableSelection',
  path: '/TableSelection',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanQRRoute = ScanQRRouteImport.update({
  id: '/ScanQR',
  path: '/ScanQR',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/LandingPage',
  path: '/LandingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const EditValueRoute = EditValueRouteImport.update({
  id: '/EditValue',
  path: '/EditValue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/AdminPage',
  path: '/AdminPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AddValueRoute = AddValueRouteImport.update({
  id: '/AddValue',
  path: '/AddValue',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRouteRoute = TableRouteRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableQRPageRoute = TableQRPageRouteImport.update({
  id: '/QRPage',
  path: '/QRPage',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableAssetRoute = TableAssetRouteImport.update({
  id: '/Asset',
  path: '/Asset',
  getParentRoute: () => TableRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/table': typeof TableRouteRouteWithChildren
  '/AddValue': typeof AddValueRoute
  '/AdminPage': typeof AdminPageRoute
  '/EditValue': typeof EditValueRoute
  '/LandingPage': typeof LandingPageRoute
  '/ScanQR': typeof ScanQRRoute
  '/TableSelection': typeof TableSelectionRoute
  '/about': typeof AboutRoute
  '/table/Asset': typeof TableAssetRoute
  '/table/QRPage': typeof TableQRPageRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AddValue': typeof AddValueRoute
  '/AdminPage': typeof AdminPageRoute
  '/EditValue': typeof EditValueRoute
  '/LandingPage': typeof LandingPageRoute
  '/ScanQR': typeof ScanQRRoute
  '/TableSelection': typeof TableSelectionRoute
  '/about': typeof AboutRoute
  '/table/Asset': typeof TableAssetRoute
  '/table/QRPage': typeof TableQRPageRoute
  '/table': typeof TableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/table': typeof TableRouteRouteWithChildren
  '/AddValue': typeof AddValueRoute
  '/AdminPage': typeof AdminPageRoute
  '/EditValue': typeof EditValueRoute
  '/LandingPage': typeof LandingPageRoute
  '/ScanQR': typeof ScanQRRoute
  '/TableSelection': typeof TableSelectionRoute
  '/about': typeof AboutRoute
  '/table/Asset': typeof TableAssetRoute
  '/table/QRPage': typeof TableQRPageRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/table'
    | '/AddValue'
    | '/AdminPage'
    | '/EditValue'
    | '/LandingPage'
    | '/ScanQR'
    | '/TableSelection'
    | '/about'
    | '/table/Asset'
    | '/table/QRPage'
    | '/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AddValue'
    | '/AdminPage'
    | '/EditValue'
    | '/LandingPage'
    | '/ScanQR'
    | '/TableSelection'
    | '/about'
    | '/table/Asset'
    | '/table/QRPage'
    | '/table'
  id:
    | '__root__'
    | '/'
    | '/table'
    | '/AddValue'
    | '/AdminPage'
    | '/EditValue'
    | '/LandingPage'
    | '/ScanQR'
    | '/TableSelection'
    | '/about'
    | '/table/Asset'
    | '/table/QRPage'
    | '/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableRouteRoute: typeof TableRouteRouteWithChildren
  AddValueRoute: typeof AddValueRoute
  AdminPageRoute: typeof AdminPageRoute
  EditValueRoute: typeof EditValueRoute
  LandingPageRoute: typeof LandingPageRoute
  ScanQRRoute: typeof ScanQRRoute
  TableSelectionRoute: typeof TableSelectionRoute
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TableSelection': {
      id: '/TableSelection'
      path: '/TableSelection'
      fullPath: '/TableSelection'
      preLoaderRoute: typeof TableSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ScanQR': {
      id: '/ScanQR'
      path: '/ScanQR'
      fullPath: '/ScanQR'
      preLoaderRoute: typeof ScanQRRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LandingPage': {
      id: '/LandingPage'
      path: '/LandingPage'
      fullPath: '/LandingPage'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/EditValue': {
      id: '/EditValue'
      path: '/EditValue'
      fullPath: '/EditValue'
      preLoaderRoute: typeof EditValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminPage': {
      id: '/AdminPage'
      path: '/AdminPage'
      fullPath: '/AdminPage'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AddValue': {
      id: '/AddValue'
      path: '/AddValue'
      fullPath: '/AddValue'
      preLoaderRoute: typeof AddValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/QRPage': {
      id: '/table/QRPage'
      path: '/QRPage'
      fullPath: '/table/QRPage'
      preLoaderRoute: typeof TableQRPageRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/Asset': {
      id: '/table/Asset'
      path: '/Asset'
      fullPath: '/table/Asset'
      preLoaderRoute: typeof TableAssetRouteImport
      parentRoute: typeof TableRouteRoute
    }
  }
}

interface TableRouteRouteChildren {
  TableAssetRoute: typeof TableAssetRoute
  TableQRPageRoute: typeof TableQRPageRoute
  TableIndexRoute: typeof TableIndexRoute
}

const TableRouteRouteChildren: TableRouteRouteChildren = {
  TableAssetRoute: TableAssetRoute,
  TableQRPageRoute: TableQRPageRoute,
  TableIndexRoute: TableIndexRoute,
}

const TableRouteRouteWithChildren = TableRouteRoute._addFileChildren(
  TableRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableRouteRoute: TableRouteRouteWithChildren,
  AddValueRoute: AddValueRoute,
  AdminPageRoute: AdminPageRoute,
  EditValueRoute: EditValueRoute,
  LandingPageRoute: LandingPageRoute,
  ScanQRRoute: ScanQRRoute,
  TableSelectionRoute: TableSelectionRoute,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
